# Static Gospel - alacritty (0.13+)
# static gospel: full-chroma occult neon over deep voids

[colors.primary]
background = "#130420"
foreground = "#f5f5ff"

[colors.cursor]
text   = "#130420"
cursor = "#37f499"

[colors.selection]
text       = "#dbdcf2"
background  = "#4b3f58"

[colors.normal]
black   = "#26233a"
red     = "#ff3860"
green   = "#37f499"
yellow  = "#ffce54"
blue    = "#9d6bff"
magenta = "#fa4fbc"
cyan    = "#04d1f9"
white   = "#dbdcf2"

[colors.bright]
black   = "#6e7487"
red     = "#ff5c78"
green   = "#69f8b3"
yellow  = "#ffe08a"
blue    = "#b892ff"
magenta = "#ff86d4"
cyan    = "#66e4fd"
white   = "#f5f5ff"
