# Static Gospel - wezterm
# place in ~/.config/wezterm/colors/, then: config.color_scheme = "Static Gospel"

[metadata]
name = "Static Gospel"
author = "Sam Lightbody"

[colors]
foreground = "#f5f5ff"
background = "#130420"
cursor_bg = "#37f499"
cursor_fg = "#130420"
cursor_border = "#37f499"
selection_fg = "#dbdcf2"
selection_bg = "#4b3f58"
ansi = ["#26233a", "#ff3860", "#37f499", "#ffce54", "#9d6bff", "#fa4fbc", "#04d1f9", "#dbdcf2"]
brights = ["#6e7487", "#ff5c78", "#69f8b3", "#ffe08a", "#b892ff", "#ff86d4", "#66e4fd", "#f5f5ff"]
