# Static Gospel Lifted - wezterm
# place in ~/.config/wezterm/colors/, then: config.color_scheme = "Static Gospel Lifted"

[metadata]
name = "Static Gospel Lifted"
author = "Sam Lightbody"

[colors]
foreground = "#f5f5ff"
background = "#0c2126"
cursor_bg = "#37f499"
cursor_fg = "#0c2126"
cursor_border = "#37f499"
selection_fg = "#dbdcf2"
selection_bg = "#2f4a51"
ansi = ["#26363d", "#ff3860", "#37f499", "#ffce54", "#9d6bff", "#fa4fbc", "#04d1f9", "#dbdcf2"]
brights = ["#6e7487", "#ff5c78", "#69f8b3", "#ffe08a", "#b892ff", "#ff86d4", "#66e4fd", "#f5f5ff"]
