# Static Gospel Lifted - kitty
# include from kitty.conf:  include ./static-gospel-lifted.conf

background            #0c2126
foreground            #f5f5ff
cursor                #37f499
cursor_text_color     #0c2126
selection_background  #2f4a51
selection_foreground  #dbdcf2
url_color             #ff8506

active_border_color    #04d1f9
inactive_border_color  #6e7487
active_tab_background   #0c2126
active_tab_foreground   #f5f5ff
inactive_tab_background #11272f
inactive_tab_foreground #6e7487

color0  #26363d
color8  #6e7487
color1  #ff3860
color9  #ff5c78
color2  #37f499
color10 #69f8b3
color3  #ffce54
color11 #ffe08a
color4  #9d6bff
color12 #b892ff
color5  #fa4fbc
color13 #ff86d4
color6  #04d1f9
color14 #66e4fd
color7  #dbdcf2
color15 #f5f5ff
