# Static Gospel Void Lifted - kitty
# include from kitty.conf:  include ./static-gospel-void-lifted.conf

background            #190a24
foreground            #f5f5ff
cursor                #37f499
cursor_text_color     #190a24
selection_background  #4c3f58
selection_foreground  #dbdcf2
url_color             #e87500

active_border_color    #04d1f9
inactive_border_color  #6e7487
active_tab_background   #190a24
active_tab_foreground   #f5f5ff
inactive_tab_background #211f30
inactive_tab_foreground #6e7487

color0  #333048
color8  #6e7487
color1  #ff3860
color9  #ff5c78
color2  #37f499
color10 #69f8b3
color3  #ffce54
color11 #ffe08a
color4  #9d6bff
color12 #b892ff
color5  #fa4fbc
color13 #ff86d4
color6  #04d1f9
color14 #66e4fd
color7  #dbdcf2
color15 #f5f5ff
