# Static Gospel - kitty
# include from kitty.conf:  include ./static-gospel.conf

background            #130420
foreground            #ebfafa
cursor                #37f499
cursor_text_color     #130420
selection_background  #413d51
selection_foreground  #e0def4
url_color             #b48eff

active_border_color    #04d1f9
inactive_border_color  #26233a
active_tab_background   #130420
active_tab_foreground   #ebfafa
inactive_tab_background #1f1d2e
inactive_tab_foreground #6e7487

color0  #26233a
color8  #6e7487
color1  #ff3860
color9  #ff5c78
color2  #37f499
color10 #69f8b3
color3  #ffce54
color11 #ffe08a
color4  #9d6bff
color12 #b892ff
color5  #b48eff
color13 #ff86d4
color6  #04d1f9
color14 #66e4fd
color7  #e0def4
color15 #ebfafa
