# Static Gospel Void - tmux
# source this from tmux.conf: source-file ~/.config/tmux/static-gospel-void.conf

set -g window-style 'bg=#17112b'
set -g window-active-style 'bg=#0e0218'
set -g pane-border-style 'fg=#26233a'
set -g pane-active-border-style 'bold,fg=#04d1f9'
