# Static Gospel Drowned - tmux
# source this from tmux.conf: source-file ~/.config/tmux/static-gospel-drowned.conf

set -g window-style 'bg=#1a272d'
set -g window-active-style 'bg=#111a1e'
set -g pane-border-style 'fg=#293338'
set -g pane-active-border-style 'bold,fg=#04d1f9'
