# Static Gospel Drowned - tmux
# source this from tmux.conf: source-file ~/.config/tmux/static-gospel-drowned.conf

set -g window-style 'bg=#0f2329'
set -g window-active-style 'bg=#08161a'
set -g pane-border-style 'fg=#202e34'
set -g pane-active-border-style 'bold,fg=#04d1f9'
