# Static Gospel Void Lifted - foot
# include from foot.ini:  include=~/.config/foot/static-gospel-void-lifted.ini

[cursor]
color=251631 37f499

[colors]
background=251631
foreground=ebfafa
selection-foreground=e0def4
selection-background=474358

regular0=333048
regular1=ff3860
regular2=37f499
regular3=ffce54
regular4=9d6bff
regular5=b48eff
regular6=04d1f9
regular7=e0def4

bright0=6e7487
bright1=ff5c78
bright2=69f8b3
bright3=ffe08a
bright4=b892ff
bright5=ff86d4
bright6=66e4fd
bright7=ebfafa
